name: Test Example Repositories
on: [push]
jobs:
  test:
    name: Test Example Repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [basic, basic-cdn, basic-ts]
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        working-directory: ${{ matrix.dir }}
        run: yarn install
      - name: Run Tests
        working-directory: ${{ matrix.dir }}
        run: CI=true yarn test
